{% set version = "1.1.1" %}

package:
  name: straglr
  version: {{ version }}

source:
  url: https://github.com/bcgsc/straglr/archive/refs/tags/v1.1.1.tar.gz
  sha256: 1161a80f6f2fa5cb9cd4db4869e29e633b2504e32394b37b88822a733a860953

build:
  entry_points:
    - straglr.py=straglr:main
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - trf
    - blast

test:
  imports:
    - straglr
  commands:
    - straglr.py --help

about:
  home: https://github.com/bcgsc/straglr
  license: MIT License
  summary: 'Short-tandem repeat genotyping using long reads'
  license_family: GPL3
  
extra:
  recipe-maintainers:
    - wdecoster
  identifiers:
    - doi:10.1186/s13059-021-02447-3
