{% set name = "Patchwork" %}
{% set version = "0.1.2" %}

package:
 name: {{ name|lower }}
 version: {{ version }}

source: 
 url: https://github.com/fethalen/Patchwork/archive/v0.1.2-pre-alpha4.tar.gz
 sha256: afb4333ab36f680feacde340ea2275e5813354a93c50fdd8a9e24a0976c453aa

build:
 number: 0

requirements:
 build: 
  - {{ compiler('c') }}
  #- gcc_linux-64 9.3.0 h1ee779e_30
  - julia >=1.6

test:
 commands: 
  - patchwork --help

about:
 home: https://github.com/fethalen/Patchwork
 doc_url: https://github.com/fethalen/Patchwork#readme
 license: GPL3
 license_file: LICENSE
 summary: "Alignment-based Exon Retrieval and Concatenation with Phylogenomic Applications"