{% set name = "Patchwork" %}
{% set version = "0.1.2" %}

package:
 name: {{ name|lower }}
 version: {{ version }}

source: 
 url: https://github.com/fethalen/Patchwork/archive/v0.1.2-pre-alpha8.tar.gz
 sha256: d67ea44e6eb12e2ecd7f9edf8cbb5e94fd6245f477853b408b7531324a119fea

build:
 number: 0

requirements:
 build: 
  - {{ compiler('c') }}
  - julia =1.6.2
 run:
  - diamond >=2.0.10

test:
 commands: 
  - patchwork --help

about:
 home: https://github.com/fethalen/Patchwork
 doc_url: https://github.com/fethalen/Patchwork#readme
 license: GPL3
 license_file: LICENSE
 summary: "Alignment-based Exon Retrieval and Concatenation with Phylogenomic Applications"