{% set name = "Patchwork" %}
{% set version = "0.1.2" %}

package:
 name: {{ name|lower }}
 version: {{ version }}

source: 
 url: https://github.com/fethalen/Patchwork/archive/v0.1.2-pre-alpha3.tar.gz
 sha256: a6c849b3b4e0f3c04f47dc539adc32aa4d7f6cc55154a6e3e9b424c86203a771

build:
 number: 0

requirements:
 build: 
  - gcc
  - julia >=1.6

test:
 commands: 
  - patchwork --help

about:
 home: https://github.com/fethalen/Patchwork
 doc_url: https://github.com/fethalen/Patchwork#readme
 license: GPL3
 license_file: LICENSE
 summary: "Alignment-based Exon Retrieval and Concatenation with Phylogenomic Applications"