{% set name = "bioframe" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7fd986ecb4d3f8cf343682587703fc3e6522f9c5c36591f3b773e923c5667927

build:
  noarch: python
  number: 0
  script: "touch requirements.txt && {{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - numpy >=1.9
    - pandas >=0.17
    - pyfaidx
    - pairix
    - pysam
    - python
    - requests
    - six
    - cytoolz

test:
  imports:
    - bioframe
    - bioframe.io

about:
  home: "https://github.com/mirnylab/bioframe"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Pandas utilities for tab-delimited and other genomic files"
  doc_url: https://bioframe.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - abretaud
