{% set version = "0.7.4" %}
{% set sha256 = "1c498d98bac0c59a4d49bfc1bd276742b9c330b6ece1299973367e23b54cb2a4" %}

package:
  name: perbase
  version: {{ version }}

source:
  url: https://github.com/sstadick/perbase/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - rust >=1.42
    - clangdev
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
    - make
  host:
    - curl
    - openssl
    - zlib
    - bzip2
    - xz
    - clangdev
  run:
    - curl
    - openssl
    - zlib
    - bzip2
    - xz

test:
  commands:
    - perbase --help

about:
  home: https://github.com/sstadick/perbase
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Per-base metrics on BAM/CRAM files.
