{% set version = "0.14.22" %}
{% set github = "https://github.com/acidgenomics/r-basejump" %}

package:
  name: r-basejump
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 5b171c4ab075ae721fc54086da5bc6ec94a2d8ea22c41b9a7c68af2789b8038f

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base >=4.0
    # Imports:
    - r-acidbase >=0.3.14
    - r-acidcli >=0.1.1
    - r-acidexperiment >=0.1.12
    - r-acidgenerics >=0.5.18
    - r-acidgenomes >=0.2.14
    - r-acidmarkdown >=0.1.1
    - r-acidplyr >=0.1.20
    - r-acidsinglecell >=0.1.7
    - r-pipette >=0.6.2
    - r-stringr >=1.4.0
    - r-syntactic >=0.4.5
  run:
    # Depends:
    - r-base >=4.0
    # Imports:
    - r-acidbase >=0.3.14
    - r-acidcli >=0.1.1
    - r-acidexperiment >=0.1.12
    - r-acidgenerics >=0.5.18
    - r-acidgenomes >=0.2.14
    - r-acidmarkdown >=0.1.1
    - r-acidplyr >=0.1.20
    - r-acidsinglecell >=0.1.7
    - r-pipette >=0.6.2
    - r-stringr >=1.4.0
    - r-syntactic >=0.4.5

test:
  commands:
    - $R -e "library('basejump')"

about:
  home: https://r.acidgenomics.com/packages/basejump/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Base functions for bioinformatics and R package development.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
